[[redirects]]
  from = "https://gnazario.netlify.com"
  to = "https://gnazar.io"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "https://blog.gnazar.io"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/:splat"
